#! /usr/bin/env python
# -*- coding: UTF-8 -*
# vim: set foldmethod=marker:

# imports {{{
#from Guzuta.gui import *
#from Guzuta import *
import guzuta
# }}}

# main {{{
if __name__ == '__main__':
  g = guzuta.gui()
  #dir()
# }}}

